### ISSUE TITLE
Getting Started doesn't work

### ISSUE THREAD

**Issue by RaringCoder** [andyhoyle/Crucial-CQRS#1]
Hi mate,

So I installed the latest node, ran npm install bower, but the bower install step fails with "bower is not a recognised command". Trying to open the solution in VS 2013 causing an unhandled error and the app shuts down, is there a particular Update required or external tool set?

**Comment by andyhoyle** [comment]
You will need .Net 4.5 installed, VS2013 configured to restore NuGet packages on build, and a SQL Server instance available and configured in `./API/web.config`, but no other special dependencies.

Your problem seems similar to this [link](http://stackoverflow.com/questions/21732447/bower-command-not-found-windows)

This are the steps I followed:
`git clone https://github.com/andyhoyle/Crucial-CQRS.git`
`cd Crucial-CQRS\Web`
`npm install -g bower` (This installs bower globally)
`bower install`

Then open ./Web.sln and right-click solution and choose startup projects:
![image](https://cloud.githubusercontent.com/assets/454471/6677955/9632c678-cc2c-11e4-96c0-2cd4cd5b336c.png)

Then hit play and navigate to: http://localhost:6307/

If you have the exception that would help diagnose the issue.

**Comment by andyhoyle** [comment]
Need to add -g flag to the instructions in readme:
`npm install bower`
should be
`npm install -g bower`

**Comment by andyhoyle** [comment]
Changed Readme.md to correct bower install command
